# Generated by Django 3.1.6 on 2021-02-21 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0010_auto_20210214_1852'),
        ('watch_list', '0003_auto_20210221_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movielist'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
