# Generated by Django 3.1.6 on 2021-02-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Write about your hobbies'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_name',
            field=models.CharField(default='Show Name', max_length=250),
        ),
    ]
