# Generated by Django 3.1.6 on 2021-02-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210218_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_name',
            field=models.CharField(default='Show Name', help_text='Display name', max_length=250),
        ),
    ]
