# Generated by Django 3.1.6 on 2021-02-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='movie_actor',
            unique_together={('movie', 'genre')},
        ),
    ]
