# Generated by Django 3.1.6 on 2021-02-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210213_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_actor',
            name='actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='movies.actor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie_actor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.movielist'),
        ),
        migrations.AlterUniqueTogether(
            name='movie_actor',
            unique_together={('movie', 'actor')},
        ),
        migrations.RemoveField(
            model_name='movie_actor',
            name='genre',
        ),
    ]
