# Generated by Django 3.1.6 on 2021-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_genre', '0001_initial'),
        ('movies', '0008_auto_20210214_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='genre',
            field=models.ManyToManyField(related_name='movie_genre', to='movie_genre.Genre'),
        ),
    ]
