# Generated by Django 3.1.6 on 2021-02-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210214_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='Actor',
            field=models.ManyToManyField(related_name='actor_movie', through='movies.Movie_Actor', to='movies.Actor'),
        ),
    ]
