# Generated by Django 3.1.6 on 2021-03-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20210315_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rec',
            name='recommended',
        ),
    ]
